version: "3"
services:
  krakend_ee:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    #image: krakend/krakend-ee:2.6-watch #(don't use for production)
    image: devopsfaith/krakend
    volumes:
      - ./config/krakend:/etc/krakend
     
      
    ports:
      - "1234:1234"
      - "8080:8080"
    command: ["run", "-d", "-c", "krakend.json"]
    # Uncomment to automatically compile using flexible configuration
    #command: ["run", "-d", "-c", "./extended/krakend.tmpl"]
    #environment:
    #  - "FC_CONFIG=/etc/krakend/fc_config.json"
    #  - "FC_DEBUG=true"
    depends_on:
      - jaeger

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    volumes:
      - "./config/telemetry-dashboards/grafana/datasources/prometheus-tempo.yml:/etc/grafana/provisioning/datasources/prometheus-tempo.yml"
      - "./config/telemetry-dashboards/grafana/krakend/for-prometheus.json:/var/lib/grafana/dashboards/krakend/for-prometheus.json"
      - "./config/telemetry-dashboards/grafana/dashboards/all.yml:/etc/grafana/provisioning/dashboards/all.yml"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./config/telemetry-dashboards/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  jaeger:
    image: jaegertracing/all-in-one:1
    environment:
      - "COLLECTOR_OTLP_ENABLED=true"
    ports:
      - "16686:16686"
      - "14268:14268"
      - "64317:4317"  # otlp grpc
      - "64318:4318"  # otlp grpc
